version: "3.3"
services:
  websocket:
    container_name: websocket
    restart: unless-stopped
    image: websocket
    command: python app/main.py
    build: .
    environment:
      - SERVICE_PORT=80
networks:
  default:
    external: true
    name: kavianex
