version: "3.3"
services:
  websocket:
    container_name: websocket
    restart: unless-stopped
    image: websocket
    command: python app/main.py
    build: .
    ports:
      - "127.0.0.1:8080:80"
    env_file:
      - .env
networks:
  default:
    external: true
    name: kavianex
